/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conef;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amigo
 */
public class PEDIDO_IMP extends javax.swing.JFrame implements Printable{
    private static final long serialVersionUID = 752647229562222227L;
ControlAcceso conAcc = new ControlAcceso();
    DefaultTableModel modelo;
    DefaultTableModel modeloDatos;
    DefaultTableModel modeloTabla;

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public void setModelo(DefaultTableModel modelo) {
        this.modelo = modelo;
    }
    
    public Informacion getInfo() {
        return info;
    }

    public void setInfo(Informacion info) {
        this.info = info;
    }
    
    Informacion info = new Informacion();
    
    void LlenaHoja(int fila){
        int noVale=Integer.parseInt(modelo.getValueAt(fila, 0).toString());
        System.out.println("vale "+noVale);
        modeloDatos=conAcc.obtenerPedidoImprimir(info.getConexion(), noVale);
        modeloTabla=conAcc.obtenerPedidoImprimirTabla(info.getConexion(), noVale);
        String nomCli=modeloDatos.getValueAt(0, 3).toString()+" "+modeloDatos.getValueAt(0, 4).toString()+" "+modeloDatos.getValueAt(0, 5).toString();
        String nomAdm=modeloDatos.getValueAt(0, 7).toString()+" "+modeloDatos.getValueAt(0, 8).toString()+" "+modeloDatos.getValueAt(0, 9).toString();
        
        ETIQUETA_NOVALE.setText(modeloDatos.getValueAt(0, 0).toString());
        ETIQUETA_FECHA.setText(modeloDatos.getValueAt(0, 1).toString());
        ETIQUETA_NOMBRE_COMPLETO.setText(nomCli);
        ETIQUETA_COMERCIO.setText(modeloDatos.getValueAt(0, 6).toString());
        ETIQUETA_NOMADM_COMPLETO.setText(nomAdm);
        ETIQUETA_TOTAL.setText(modeloDatos.getValueAt(0, 2).toString());
        
        TABLA.setModel(modeloTabla);
    }
    
    void LlenaHojaNoVale(int noVale){
        //int noVale=Integer.parseInt(modelo.getValueAt(fila, 0).toString());
        System.out.println("vale "+noVale);
        modeloDatos=conAcc.obtenerPedidoImprimir(info.getConexion(), noVale);
        modeloTabla=conAcc.obtenerPedidoImprimirTabla(info.getConexion(), noVale);
        String nomCli=modeloDatos.getValueAt(0, 3).toString()+" "+modeloDatos.getValueAt(0, 4).toString()+" "+modeloDatos.getValueAt(0, 5).toString();
        String nomAdm=modeloDatos.getValueAt(0, 7).toString()+" "+modeloDatos.getValueAt(0, 8).toString()+" "+modeloDatos.getValueAt(0, 9).toString();
        
        ETIQUETA_NOVALE.setText(modeloDatos.getValueAt(0, 0).toString());
        ETIQUETA_FECHA.setText(modeloDatos.getValueAt(0, 1).toString());
        ETIQUETA_NOMBRE_COMPLETO.setText(nomCli);
        ETIQUETA_COMERCIO.setText(modeloDatos.getValueAt(0, 6).toString());
        ETIQUETA_NOMADM_COMPLETO.setText(nomAdm);
        ETIQUETA_TOTAL.setText(modeloDatos.getValueAt(0, 2).toString());
        
        TABLA.setModel(modeloTabla);
        
        
        
        
    }
    
    public PEDIDO_IMP() {
        initComponents();
        TABLA.setDefaultEditor(Object.class, null);
        TABLA.getTableHeader().setReorderingAllowed(false) ;
        
        this.pintarImagen(LOGOCELFIMEX, "/images/logoCelfimex.png");
        this.pintarImagen(LOGOCONEF, "/images/logo.png");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hoja = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ETIQUETA_NOVALE = new javax.swing.JLabel();
        ETIQUETA_COMERCIO = new javax.swing.JLabel();
        ETIQUETA_NOMBRE_COMPLETO = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ETIQUETA_NOMADM_COMPLETO = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ETIQUETA_TOTAL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ETIQUETA_FECHA = new javax.swing.JLabel();
        BOTON_IMPRIMIR = new javax.swing.JButton();
        BOTON_REGRESAR = new javax.swing.JButton();
        LOGOCELFIMEX = new javax.swing.JLabel();
        LOGOCONEF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IMPRESION");
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        Hoja.setBackground(new java.awt.Color(255, 255, 255));
        Hoja.setName("Hoja"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("No. Vale");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PEDIDO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cliente:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Comercio:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ETIQUETA_NOVALE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ETIQUETA_NOVALE.setText(" ");

        ETIQUETA_COMERCIO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ETIQUETA_COMERCIO.setText(" ");

        ETIQUETA_NOMBRE_COMPLETO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ETIQUETA_NOMBRE_COMPLETO.setText(" ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Administrador:");

        ETIQUETA_NOMADM_COMPLETO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ETIQUETA_NOMADM_COMPLETO.setText(" ");

        TABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TABLA);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Total");

        ETIQUETA_TOTAL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ETIQUETA_TOTAL.setText(" ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Fecha  de Pedido");

        ETIQUETA_FECHA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ETIQUETA_FECHA.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ETIQUETA_NOVALE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ETIQUETA_NOMBRE_COMPLETO, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ETIQUETA_COMERCIO, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ETIQUETA_NOMADM_COMPLETO, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ETIQUETA_TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ETIQUETA_FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(288, 288, 288))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ETIQUETA_NOVALE)
                    .addComponent(jLabel9)
                    .addComponent(ETIQUETA_FECHA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ETIQUETA_NOMBRE_COMPLETO))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ETIQUETA_COMERCIO))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ETIQUETA_NOMADM_COMPLETO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ETIQUETA_TOTAL))
                .addGap(19, 19, 19))
        );

        BOTON_IMPRIMIR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BOTON_IMPRIMIR.setText("IMPRIMIR");
        BOTON_IMPRIMIR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BOTON_IMPRIMIRFocusLost(evt);
            }
        });
        BOTON_IMPRIMIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_IMPRIMIRActionPerformed(evt);
            }
        });

        BOTON_REGRESAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BOTON_REGRESAR.setText("Regresar");
        BOTON_REGRESAR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BOTON_REGRESARFocusLost(evt);
            }
        });
        BOTON_REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_REGRESARActionPerformed(evt);
            }
        });

        LOGOCELFIMEX.setText("jLabel1");

        LOGOCONEF.setText("jLabel1");

        javax.swing.GroupLayout HojaLayout = new javax.swing.GroupLayout(Hoja);
        Hoja.setLayout(HojaLayout);
        HojaLayout.setHorizontalGroup(
            HojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HojaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BOTON_REGRESAR)
                .addGap(153, 153, 153)
                .addComponent(BOTON_IMPRIMIR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HojaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(HojaLayout.createSequentialGroup()
                        .addComponent(LOGOCELFIMEX, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LOGOCONEF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        HojaLayout.setVerticalGroup(
            HojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HojaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(HojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOGOCELFIMEX, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOGOCONEF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(HojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BOTON_REGRESAR)
                    .addComponent(BOTON_IMPRIMIR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Hoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        //BOTON_IMPRIMIR.setVisible(false);
    }//GEN-LAST:event_formFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
       // BOTON_IMPRIMIR.setVisible(true);
    }//GEN-LAST:event_formFocusGained

    private void BOTON_IMPRIMIRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BOTON_IMPRIMIRFocusLost

    }//GEN-LAST:event_BOTON_IMPRIMIRFocusLost

    private void BOTON_IMPRIMIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_IMPRIMIRActionPerformed
        
        printComponent(Hoja);
        
        
        
    }//GEN-LAST:event_BOTON_IMPRIMIRActionPerformed

    private void BOTON_REGRESARFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BOTON_REGRESARFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTON_REGRESARFocusLost

    private void BOTON_REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_REGRESARActionPerformed
        PEDIDO_CONSULTAR ventana= new PEDIDO_CONSULTAR();
        ventana.setInfo(info);
        ventana.obtenerFilas();
        ventana.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_BOTON_REGRESARActionPerformed

    public void printComponent(JPanel component){
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName(" Print Component ");

        pj.setPrintable (new Printable() {    
          public int print(Graphics pg, PageFormat pf, int pageNum){
            if (pageNum > 0){
            return Printable.NO_SUCH_PAGE;
            }

            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            component.paint(g2);
            return Printable.PAGE_EXISTS;
          }
        });
        if (pj.printDialog() == false)
        return;

        try {
              pj.print();
        } catch (PrinterException ex) {
              // handle exception
        }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PEDIDO_IMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PEDIDO_IMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PEDIDO_IMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PEDIDO_IMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PEDIDO_IMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTON_IMPRIMIR;
    private javax.swing.JButton BOTON_REGRESAR;
    private javax.swing.JLabel ETIQUETA_COMERCIO;
    private javax.swing.JLabel ETIQUETA_FECHA;
    private javax.swing.JLabel ETIQUETA_NOMADM_COMPLETO;
    private javax.swing.JLabel ETIQUETA_NOMBRE_COMPLETO;
    private javax.swing.JLabel ETIQUETA_NOVALE;
    private javax.swing.JLabel ETIQUETA_TOTAL;
    private javax.swing.JPanel Hoja;
    private javax.swing.JLabel LOGOCELFIMEX;
    private javax.swing.JLabel LOGOCONEF;
    private javax.swing.JTable TABLA;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graficos, PageFormat formatoPagina, int paginaIndex) throws PrinterException {
        if(paginaIndex==0){
            Graphics2D grafico = (Graphics2D) graficos;
            grafico.translate(formatoPagina.getImageableX(), formatoPagina.getImageableY());
            printAll(grafico);
            return PAGE_EXISTS;
        }else{
            return NO_SUCH_PAGE;
        }
            
    }
     private ImageIcon imagen;
    private Icon icono;
    
    void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(getClass().getResource(ruta));

        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
}
